name: Template Validation Sample Workflow Win
on: 
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation_job:
    runs-on: windows-latest
    name: template validation
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'

      - uses: microsoft/template-validation-action@Latest
        id: validation
        with: 
          useDevContainer: false
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_ROLE_FOR_USER: false

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}